### ISSUE TITLE
SPI readback tests don't pass

### ISSUE THREAD

**Issue by dnadlinger** [quartiq/urukul#10]
```
~/Build/Source/urukul ((v1.3.1) $%)$ python urukul_sim.py
Traceback (most recent call last):
  File "urukul_sim.py", line 130, in <module>
    main()
  File "urukul_sim.py", line 126, in main
    special_overrides={Tristate: SimTristate, Instance: SimInstance})
  File "/Users/dpn/Build/Source/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/Users/dpn/Build/Source/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/Users/dpn/Build/Source/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "urukul_sim.py", line 105, in test
    assert ret & 0xff0000 == 0x080000, hex(ret)
AssertionError: 0x2468ac
```

**Comment by jordens** [comment]
IIRC Last time I bisected this they were broken by the v1.1 or v1.3 changes.

**Comment by dnadlinger** [comment]
Yep, the SPI changes in 44ea1cba seem to be what actually broke it (as opposed to just the test protocol revision not being up to date).
